services:
  - type: web
    name: pgadmin
    env: docker       # tells Render to build your Dockerfile
    dockerCommand: /entrypoint.sh
    envVars:
      - key: PGADMIN_DEFAULT_EMAIL
        value: admin@example.com
      - key: PGADMIN_DEFAULT_PASSWORD
        value: SuperSecret123
    plan: free
