services:
  - type: web
    name: pgadmin
    env: docker
    image: dpage/pgadmin4:latest
    dockerCommand: /entrypoint.sh
    envVars:
      - key: PGADMIN_DEFAULT_EMAIL
        value: admin@example.com
      - key: PGADMIN_DEFAULT_PASSWORD
        value: SuperSecret123
    plan: free
